[package]
name = "ecs_pause_revive_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = "0.7.5"
rusoto_core = "0.48.0"
rusoto_ecs = "0.48.0"
tokio = { version = "1.42.0", features = ["full"] }
